language: android
jdk: oraclejdk8

env:
  global:
   - ANDROID_API_LEVEL=27
   - EMULATOR_API_LEVEL=21
   - ANDROID_BUILD_TOOLS_VERSION=27.0.3
   - PATH_TO_PROJECT=Cours_Gérez_vos_données_localement_pour_avoir_une_application_100\%_offline/Partie1\&2\&3/SaveMyTrip
  matrix:
   - ANDROID_TARGET=android-24  ANDROID_ABI=armeabi-v7a

android:
  components:
    - build-tools-$ANDROID_BUILD_TOOLS_VERSION
    - $ANDROID_TARGET
    - sys-img-armeabi-v7a-$ANDROID_TARGET

before_install:
  - yes | sdkmanager "platforms;android-27"

licenses:
    - 'android-sdk-preview-license-52d11cd2'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

before_script:
  - chmod +x /$PATH_TO_PROJECT/gradlew
  - ./$PATH_TO_PROJECT/gradlew build jacocoTestReport assembleAndroidTest
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  - emulator -avd test -no-window &
  - android-wait-for-emulator
  - ./$PATH_TO_PROJECT/gradlew connectedCheck

after_success:
  - bash <(curl -s https://codecov.io/bash)
